# Generated by Django 4.2.7 on 2026-01-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_session_70d41b_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_session_15a55f_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_chatse_user_id_dcd342_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='updated_at',
        ),
    ]
