# Generated by Django 4.2.7 on 2026-01-03 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stress_score', models.PositiveSmallIntegerField()),
                ('anxiety_score', models.PositiveSmallIntegerField()),
                ('depression_score', models.PositiveSmallIntegerField()),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=16)),
                ('alert_recommended', models.BooleanField(db_index=True, default=False)),
                ('rationale_short', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('raw_llm_json', models.TextField(blank=True)),
                ('analysis_status', models.CharField(choices=[('OK', 'OK'), ('REPAIRED', 'Repaired'), ('FAILED', 'Failed')], db_index=True, default='OK', max_length=16)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='chat.chatsession')),
                ('triggering_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analysis_an_session_9087b1_idx'), models.Index(fields=['session', 'risk_level', 'created_at'], name='analysis_an_session_51fa85_idx'), models.Index(fields=['session', 'alert_recommended', 'created_at'], name='analysis_an_session_1ee4da_idx')],
            },
        ),
    ]
