# Generated by Django 4.2.7 on 2026-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisresult',
            name='analysis_an_session_9087b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysisresult',
            name='analysis_an_session_51fa85_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysisresult',
            name='analysis_an_session_1ee4da_idx',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ai_message',
            field=models.TextField(blank=True),
        ),
    ]
