# Generated by Django 4.2.7 on 2026-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alertevent',
            name='alerts_aler_user_id_d7d75c_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertevent',
            name='alerts_aler_user_id_e460f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='alerts_emer_user_id_b40f3b_idx',
        ),
        migrations.RemoveField(
            model_name='alertevent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='risk_level',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
