# Generated by Django 4.2.7 on 2026-01-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_alertevent_alerts_aler_user_id_d7d75c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=16),
        ),
    ]
